### ISSUE TITLE
SCC becomes NAN

### ISSUE THREAD

**Issue by Patricia886** [CR-Gjx/SCC#1]
Hello, I use SCC Loss in my image translation task, but after 1000 iterations, SCC loss becomes NAN. What is the problem

**Comment by CR-Gjx** [comment]
Hello, thanks for the interest in my work! May I know what datasets you used in your experiment? likewise, what was the value of `lambda_SCC ` that you employed in your experiment?

**Comment by Patricia886** [comment]
> Hello, thanks for the interest in my work! May I know what datasets you used in your experiment? likewise, what was the value of `lambda_SCC ` that you employed in your experiment?

The same happens when I use the FFHQ dataset as the source domain and the sketches as the target domain style, as well as the LSUN Church as the source domain and Haunted Houses as the target domain style. Following your paper, lambda_SCC is set to 5

**Comment by CR-Gjx** [comment]
I see. You can incorporate this the public file in [GcGANCan](https://github.com/hufu6371/GcGAN/tree/master/models) codebase. In order to localize the problem, can you share more details with me? e.g. image_size or other modifications you have done.  Note that in GcGAN, we always train the model 200 epochs, but there is no NAN during the training process.

**Comment by Patricia886** [comment]
> I see. You can incorporate this the public file in [GcGANCan](https://github.com/hufu6371/GcGAN/tree/master/models) codebase. In order to localize the problem, can you share more details with me? e.g. image_size or other modifications you have done. Note that in GcGAN, we always train the model 200 epochs, but there is no NAN during the training process.

Our image_size is 3*256*256, and batch size is 4. In addition, I did not modify other content in the code. The SCC loss of LSUN Church and FFHQ changes to NAN at 1000+ epochs and 600+ epochs respectively.

**Comment by CR-Gjx** [comment]
Thanks for sharing the details with me! The batch size is set to 1 in my experiments. In addition, can you further share the results before the collapse? e.g. image results/ SCC loss value.

**Comment by CR-Gjx** [comment]
Solved
